/**
 * Mock data for Finance Manager Dashboard
 * This file provides sample data for development and testing
 * Replace with real API calls when backend is ready
 */

export const mockFundSourcesOverview = {
    collegeFunds: {
        totalAllocated: 50000000,    // ₹5 Crores
        totalUsed: 32000000,         // ₹3.2 Crores
        remainingBalance: 18000000,  // ₹1.8 Crores
    },
    pfmsFunds: {
        totalAllocated: 75000000,    // ₹7.5 Crores
        totalUsed: 45000000,         // ₹4.5 Crores
        remainingBalance: 30000000,  // ₹3 Crores
    },
};

export const mockDepartments = [
    { id: '1', name: 'Centre for Nano Science and Nanotechnology' },
    { id: '2', name: 'Centre of Excellence for Energy Research' },
    { id: '3', name: 'Centre for Waste Management' },
    { id: '4', name: 'Centre for Climate Studies' },
    { id: '5', name: 'Centre for Molecular and Nanomedical Sciences' },
    { id: '6', name: 'Centre for Drug Discovery and Development' },
    { id: '7', name: 'Centre of Excellence for Additive Manufacturing' },
    { id: '8', name: 'Centre for Indian System of Medicine' },
];

export const mockDepartmentFunding = {
    '1': [
        {
            id: 1,
            departmentName: 'Centre for Nano Science and Nanotechnology',
            fundSource: 'COLLEGE',
            totalAllocated: 10000000,
            amountReleased: 2000000,
            remainingBalance: 8000000,
        },
        {
            id: 2,
            departmentName: 'Centre for Nano Science and Nanotechnology',
            fundSource: 'PFMS',
            totalAllocated: 15000000,
            amountReleased: 5000000,
            remainingBalance: 10000000,
        },
    ],
    '2': [
        {
            id: 3,
            departmentName: 'Centre of Excellence for Energy Research',
            fundSource: 'COLLEGE',
            totalAllocated: 12000000,
            amountReleased: 6000000,
            remainingBalance: 6000000,
        },
    ],
    // Add other departments as needed
};

// Project statuses
export const PROJECT_STATUSES = {
    PENDING_DEAN_APPROVAL: 'Pending Dean Approval',
    APPROVED_BY_DEAN: 'Approved by Dean',
    FUND_RELEASED: 'Fund Released',
    CHEQUE_RELEASED: 'Cheque Released',
    COMPLETED: 'Completed',
    REJECTED: 'Rejected',
};

// Mock projects data
export const mockProjects = [
    {
        id: 1,
        projectTitle: 'Nanomaterial Synthesis for Drug Delivery',
        departmentId: '1',
        departmentName: 'Centre for Nano Science and Nanotechnology',
        principalInvestigator: 'Dr. Anjali Gupta',
        requestedAmount: 8500000,
        approvedAmount: 8000000,
        currentStatus: 'APPROVED_BY_DEAN',
        fundSource: 'PFMS',
        submittedDate: '2024-01-28',
        lastUpdated: '2024-02-03',
        description: 'Development of novel nanomaterials for targeted drug delivery systems',
    },
    {
        id: 2,
        projectTitle: 'Solar Energy Storage Optimization',
        departmentId: '2',
        departmentName: 'Centre of Excellence for Energy Research',
        principalInvestigator: 'Dr. Robert Wilson',
        requestedAmount: 6000000,
        approvedAmount: 6000000,
        currentStatus: 'FUND_RELEASED',
        fundSource: 'COLLEGE',
        submittedDate: '2024-01-15',
        lastUpdated: '2024-02-02',
        fundReleasedDate: '2024-02-02',
        fundReleasedAmount: 6000000,
        transactionId: 'TXN2024020200987',
        description: 'Optimizing battery storage systems for solar energy applications',
    },
    {
        id: 3,
        projectTitle: 'Waste-to-Energy Conversion Plant Pilot',
        departmentId: '3',
        departmentName: 'Centre for Waste Management',
        principalInvestigator: 'Dr. Sarah Thomas',
        requestedAmount: 4500000,
        approvedAmount: 4000000,
        currentStatus: 'APPROVED_BY_DEAN',
        fundSource: 'PFMS',
        submittedDate: '2024-01-20',
        lastUpdated: '2024-02-01',
        description: 'Pilot plant for converting organic waste to biogas',
    },
    {
        id: 4,
        projectTitle: 'Coastal Climate Monitoring Network',
        departmentId: '4',
        departmentName: 'Centre for Climate Studies',
        principalInvestigator: 'Dr. James Chen',
        requestedAmount: 3000000,
        approvedAmount: 3000000,
        currentStatus: 'APPROVED_BY_DEAN',
        fundSource: 'COLLEGE',
        submittedDate: '2024-01-10',
        lastUpdated: '2024-01-25',
        description: 'Network of sensors for monitoring coastal climate parameters',
    },
    {
        id: 5,
        projectTitle: 'Molecular Dynamics Simulation Cluster',
        departmentId: '5',
        departmentName: 'Centre for Molecular and Nanomedical Sciences',
        principalInvestigator: 'Dr. Kevin White',
        requestedAmount: 5500000,
        approvedAmount: 5500000,
        currentStatus: 'FUND_RELEASED',
        fundSource: 'PFMS',
        submittedDate: '2024-01-05',
        lastUpdated: '2024-01-30',
        fundReleasedDate: '2024-01-30',
        fundReleasedAmount: 5500000,
        transactionId: 'TXN2024013000555',
        description: 'High-performance computing cluster for molecular simulations',
    },
    {
        id: 6,
        projectTitle: 'High-Throughput Screening System',
        departmentId: '6',
        departmentName: 'Centre for Drug Discovery and Development',
        principalInvestigator: 'Dr. Lisa Patel',
        requestedAmount: 9000000,
        approvedAmount: 8500000,
        currentStatus: 'CHEQUE_RELEASED',
        fundSource: 'COLLEGE',
        submittedDate: '2023-12-15',
        lastUpdated: '2024-01-20',
        fundReleasedDate: '2024-01-15',
        fundReleasedAmount: 8500000,
        chequeNumber: 'CHQ987654',
        chequeDate: '2024-01-20',
        bankName: 'HDFC Bank',
        description: 'Automated screening system for drug discovery',
    },
    {
        id: 7,
        projectTitle: '3D Metal Printing Facility',
        departmentId: '7',
        departmentName: 'Centre of Excellence for Additive Manufacturing',
        principalInvestigator: 'Dr. Michael Brown',
        requestedAmount: 12000000,
        approvedAmount: 11000000,
        currentStatus: 'PENDING_DEAN_APPROVAL',
        fundSource: 'PFMS',
        submittedDate: '2024-02-01',
        lastUpdated: '2024-02-01',
        description: 'State-of-the-art 3D metal printing facility for aerospace components',
    },
    {
        id: 8,
        projectTitle: 'Traditional Medicine Database',
        departmentId: '8',
        departmentName: 'Centre for Indian System of Medicine',
        principalInvestigator: 'Dr. Priya Rao',
        requestedAmount: 2000000,
        approvedAmount: 1500000,
        currentStatus: 'REJECTED',
        fundSource: 'COLLEGE',
        submittedDate: '2024-01-25',
        lastUpdated: '2024-01-28',
        rejectionReason: 'Proposal needs more detailed budget breakdown',
        description: 'Digital database for traditional Indian medicinal plants',
    },
    {
        id: 9,
        projectTitle: 'Smart Grid Management System',
        departmentId: '2',
        departmentName: 'Centre of Excellence for Energy Research',
        principalInvestigator: 'Dr. Rajesh Kumar',
        requestedAmount: 4500000,
        approvedAmount: 4500000,
        currentStatus: 'PENDING_DEAN_APPROVAL',
        fundSource: 'PFMS',
        submittedDate: '2024-02-04',
        lastUpdated: '2024-02-04',
        description: 'AI-driven smart grid management for optimized power distribution',
    },
    {
        id: 10,
        projectTitle: 'Ocean Acidification Impact Study',
        departmentId: '4',
        departmentName: 'Centre for Climate Studies',
        principalInvestigator: 'Dr. Meera Reddy',
        requestedAmount: 3200000,
        approvedAmount: 3000000,
        currentStatus: 'APPROVED_BY_DEAN',
        fundSource: 'PFMS',
        submittedDate: '2024-01-18',
        lastUpdated: '2024-02-02',
        description: 'Long-term study on the impact of ocean acidification on local marine life',
    },
    {
        id: 11,
        projectTitle: 'Herbal Compilation for Diabetes',
        departmentId: '8',
        departmentName: 'Centre for Indian System of Medicine',
        principalInvestigator: 'Dr. Suresh Nair',
        requestedAmount: 2800000,
        approvedAmount: 2500000,
        currentStatus: 'FUND_RELEASED',
        fundSource: 'PFMS',
        submittedDate: '2023-11-20',
        lastUpdated: '2024-01-15',
        fundReleasedDate: '2024-01-15',
        fundReleasedAmount: 2500000,
        transactionId: 'TXN2024011500444',
        description: 'Compilation and testing of traditional herbal formulations for diabetes management',
    },
    {
        id: 12,
        projectTitle: 'Graphene Supercapacitors',
        departmentId: '1',
        departmentName: 'Centre for Nano Science and Nanotechnology',
        principalInvestigator: 'Dr. Amit Shah',
        requestedAmount: 6000000,
        approvedAmount: 6000000,
        currentStatus: 'COMPLETED',
        fundSource: 'PFMS',
        submittedDate: '2023-06-10',
        lastUpdated: '2024-01-10',
        fundReleasedDate: '2023-08-15',
        fundReleasedAmount: 6000000,
        transactionId: 'TXN2023081500123',
        description: 'Development of high-capacity graphene-based supercapacitors',
    },
    {
        id: 13,
        projectTitle: 'Bio-fuel form Algae',
        departmentId: '3',
        departmentName: 'Centre for Waste Management',
        principalInvestigator: 'Dr. Nancy Williams',
        requestedAmount: 5000000,
        approvedAmount: 4800000,
        currentStatus: 'APPROVED_BY_DEAN',
        fundSource: 'PFMS',
        submittedDate: '2024-01-22',
        lastUpdated: '2024-02-03',
        description: 'Sustainable production of bio-fuel from algal blooms in wastewater',
    },
    {
        id: 14,
        projectTitle: 'Anti-Cancer Drug Screening',
        departmentId: '6',
        departmentName: 'Centre for Drug Discovery and Development',
        principalInvestigator: 'Dr. Vikram Singh',
        requestedAmount: 7500000,
        approvedAmount: 7000000,
        currentStatus: 'REJECTED',
        fundSource: 'PFMS',
        submittedDate: '2024-01-12',
        lastUpdated: '2024-01-25',
        rejectionReason: 'Similar project already funded recently',
        description: 'High-throughput screening for potential anti-cancer compounds from marine sources',
    },
    {
        id: 15,
        projectTitle: 'Additive Manufacturing in Orthopedics',
        departmentId: '7',
        departmentName: 'Centre of Excellence for Additive Manufacturing',
        principalInvestigator: 'Dr. John Davis',
        requestedAmount: 9500000,
        approvedAmount: 9000000,
        currentStatus: 'APPROVED_BY_DEAN',
        fundSource: 'PFMS',
        submittedDate: '2024-01-28',
        lastUpdated: '2024-02-04',
        description: 'Customized orthopedic implants using additive manufacturing techniques',
    },
    {
        id: 16,
        projectTitle: 'Climate Resilient Crops',
        departmentId: '4',
        departmentName: 'Centre for Climate Studies',
        principalInvestigator: 'Dr. Lakshmi Iyer',
        requestedAmount: 4000000,
        approvedAmount: 4000000,
        currentStatus: 'PENDING_DEAN_APPROVAL',
        fundSource: 'PFMS',
        submittedDate: '2024-02-05',
        lastUpdated: '2024-02-05',
        description: 'Developing crop varieties resilient to changing climate patterns',
    },
];

// Mock Function Fund Requests
export const mockFunctionRequests = [
    {
        id: 1,
        facultyName: 'Dr. Anjali Gupta',
        department: 'Centre for Nano Science and Nanotechnology',
        functionName: 'International Conference on Nanomaterials 2024',
        description: 'Organizing a 3-day international conference with keynote speakers from top universities.',
        amount: 500000,
        status: 'APPROVED_BY_DEAN',
        requestDate: '2024-02-01',
    },
    {
        id: 2,
        facultyName: 'Dr. Robert Wilson',
        department: 'Centre of Excellence for Energy Research',
        functionName: 'Workshop on Solar Panel Efficiency',
        description: 'Hands-on workshop for students and researchers on improving solar panel efficiency.',
        amount: 150000,
        status: 'FUNDS_RELEASED',
        requestDate: '2024-01-20',
        releaseDate: '2024-01-25',
        transactionId: 'TXN_FUNC_001',
    },
    {
        id: 3,
        facultyName: 'Dr. Sarah Thomas',
        department: 'Centre for Waste Management',
        functionName: 'Seminar on Sustainable Waste Practices',
        description: 'One-day seminar focusing on community waste management strategies.',
        amount: 75000,
        status: 'APPROVED_BY_DEAN',
        requestDate: '2024-02-05',
    },
    {
        id: 4,
        facultyName: 'Dr. James Chen',
        department: 'Centre for Climate Studies',
        functionName: 'Climate Action Awareness Week',
        description: 'A week-long event with various activities to raise awareness about climate change.',
        amount: 200000,
        status: 'APPROVED_BY_DEAN',
        requestDate: '2024-02-07',
    },
];
