services:
  - type: web
    name: finance-api
    plan: free
    runtime: node
    rootDir: finance-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://college_project_db_user:fTR9h0ig5rFLiNPJg4IJoHzRB3LZ71z1@dpg-d76cnrn5r7bs73c42emg-a.singapore-postgres.render.com/college_project_db
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: FRONTEND_URL
        value: https://finance-frontend-pxh9.onrender.com

  - type: web
    name: finance-frontend
    plan: free
    runtime: node
    rootDir: finance-frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://finance-api-x1ig.onrender.com/api
      - key: PORT
        value: 10000
