const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const { getAdminDashboardData } = require('../services/pipelineMetricsService');
const asyncHandler = require('../utils/asyncHandler');

/**
 * @desc    Export financial reports in PDF or Excel format
 * @route   GET /api/v1/reports/export
 * @access  Private/Admin
 */
const exportReport = asyncHandler(async (req, res) => {
    const { fy, type } = req.query;
    const adminData = await getAdminDashboardData(fy || '2024-25');
    const stats = adminData?.data || {};
    const centres = stats.centres || [];
    const totalUsed = Number(stats.totalDisbursed ?? stats.totalUsed ?? stats.used ?? 0);

    if (type === 'pdf') {
        const doc = new PDFDocument({ margin: 50 });
        const filename = `Sathyabama_Finance_Report_${fy}.pdf`;

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

        doc.pipe(res);

        // Header
        doc.fontSize(20).text('Sathyabama Financial Report', { align: 'center' });
        doc.fontSize(12).text(`Fiscal Year: ${fy}`, { align: 'center' });
        doc.moveDown();
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();

        // Stats
        doc.fontSize(14).text('Global Allotment Summary', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(11)
           .text(`Total Allocated Budget: INR ${Number(stats.totalAllocated || 0).toLocaleString()}`)
           .text(`Total Funds Spent/Disbursed: INR ${totalUsed.toLocaleString()}`)
           .text(`Current Remaining Balance: INR ${Number(stats.remaining || 0).toLocaleString()}`)
           .text(`Year-over-Year Growth: ${Number(stats.growth || 0).toFixed(2)}%`);

        doc.moveDown();
        doc.fontSize(14).text('Centre Breakdown', { underline: true });
        doc.moveDown(0.5);
        
        centres.forEach(centre => {
            doc.fontSize(10).text(`${centre.name}: INR ${Number(centre.totalBudget || 0).toLocaleString()} (Spent: INR ${Number(centre.disbursed || 0).toLocaleString()})`);
        });

        // Footer
        const bottom = doc.page.height - 50;
        doc.fontSize(8).text('Generated by Sathyabama Finance System', 50, bottom, { align: 'center' });

        doc.end();

    } else if (type === 'excel') {
        const workbook = new ExcelJS.Workbook();
        const filename = `Sathyabama_Finance_Report_${fy}.xlsx`;
        
        const summarySheet = workbook.addWorksheet('Financial Summary');
        summarySheet.columns = [
            { header: 'Metric', key: 'metric', width: 30 },
            { header: 'Value', key: 'value', width: 20 }
        ];

        summarySheet.addRows([
            { metric: 'Fiscal Year', value: fy },
            { metric: 'Total Allocated', value: Number(stats.totalAllocated || 0) },
            { metric: 'Total Used', value: totalUsed },
            { metric: 'Remaining Balance', value: Number(stats.remaining || 0) },
            { metric: 'YoY Growth (%)', value: Number(stats.growth || 0).toFixed(2) }
        ]);

        const centreSheet = workbook.addWorksheet('Centre Breakdown');
        centreSheet.columns = [
            { header: 'Research Centre', key: 'name', width: 40 },
            { header: 'Allocated Budget', key: 'totalBudget', width: 20 },
            { header: 'Disbursed Amount', key: 'disbursed', width: 20 }
        ];

        centres.forEach(c => {
            centreSheet.addRow({
                name: c.name,
                totalBudget: Number(c.totalBudget || 0),
                disbursed: Number(c.disbursed || 0)
            });
        });

        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

        await workbook.xlsx.write(res);
        res.end();
    } else {
        res.status(400).json({ success: false, message: 'Invalid report type. Use pdf or excel.' });
    }
});

module.exports = {
    exportReport
};
